version: '3.4'

services:
  nostyleplease:
    image: nostyleplease
    build: https://github.com/diegoc-am/no-style-please
    environment:
      - JEKYLL_ENV=production
    ports:
      - 4000:4000
