version: '3.4'

services:
  nostyleplease:
    build: https://github.com/diegoc-am/no-style-please
    environment:
      - JEKYLL_ENV=production
    ports:
      - 4000:4000

# tunnel:
#     image: cloudflare/cloudflared
#     restart: unless-stopped
#     command: tunnel --no-autoupdate run
#     environment:
#       - TUNNEL_TOKEN=
#     depends_on:
#       - nostyleplease